package pw.vasilevskiy.loeuc.shared.protocol

/**
 * How much the description of a field is worth trusting.
 *
 * The distinction is the whole point of this catalogue. Most of these 248 names have never been
 * confirmed against anything, and presenting a plausible guess with the same authority as a measured
 * fact is how a reverse-engineered dashboard starts lying to its user.
 */
enum class LeaperKimStrFieldConfidence {
    /** Verified against a capture, against the firmware, or by the wheel's owner. */
    Confirmed,

    /** The name plus the observed behaviour agree, and nothing contradicts it. Not verified. */
    Likely,

    /** A reading of the name and little else. Treat as a label, not as a meaning. */
    Guess,
}

data class LeaperKimStrField(
    val tag: String,
    val ru: String,
    val en: String,
    /** Unit where it is known. Most fields print raw counts whose scale nobody has established. */
    val unit: String?,
    val confidence: LeaperKimStrFieldConfidence,
)

/**
 * What the `StR` diagnostic fields mean, as far as anyone has established.
 *
 * Covers the twelve page shapes seen across the 2026-08-11 captures. A tag that is absent is absent
 * on purpose: filling the gaps with invented descriptions would make the catalogue worse than
 * useless. Callers should show the bare tag when [describe] returns null.
 *
 * Sources and the evidence behind each `Confirmed` entry are in
 * `docs/leaperkim-str-debug-telemetry-ru.md`.
 */
object LeaperKimStrFieldCatalog {
    private fun f(
        tag: String,
        ru: String,
        en: String,
        unit: String?,
        confidence: LeaperKimStrFieldConfidence,
    ) = LeaperKimStrField(tag, ru, en, unit, confidence)

    private val Confirmed = LeaperKimStrFieldConfidence.Confirmed
    private val Likely = LeaperKimStrFieldConfidence.Likely
    private val Guess = LeaperKimStrFieldConfidence.Guess

    val all: List<LeaperKimStrField> = listOf(
        f("dKM", "Скорость со знаком", "Signed speed", "0.1 км/ч", Confirmed),
        f("AA", "Ток фазы A", "Phase A current", "0.1 А", Confirmed),
        f("AB", "Ток фазы B", "Phase B current", "0.1 А", Confirmed),
        f("AC", "Ток фазы C", "Phase C current", "0.1 А", Confirmed),
        f("V", "Напряжение батареи", "Pack voltage", "В", Confirmed),
        f("Cmo", "Температура MOS", "MOS temperature", "°C", Confirmed),
        f("Cmt", "Не температура мотора; что это — неизвестно", "Not the motor temperature; unidentified", null, Confirmed),
        f("FdHz", "Частота привода, 41.9 на км/ч", "Drive frequency, 41.9 per km/h", null, Confirmed),
        f("Out", "То же, что Vqd, в 1.3145 раза", "Same as Vqd, scaled by 1.3145", null, Confirmed),
        f("TC", "Задание момента", "Torque command", null, Confirmed),
        f("FTC", "То же задание, фильтрованное", "The same command, filtered", null, Confirmed),
        f("VD", "Напряжение по оси d; минус на разгоне", "d-axis voltage; negative under acceleration", null, Confirmed),
        f("IM", "Заглушка, всегда 60001", "Placeholder, always 60001", null, Confirmed),
        f("Fs", "Заглушка, всегда 60001", "Placeholder, always 60001", null, Confirmed),
        f("VQ", "Напряжение по оси q", "q-axis voltage", null, Likely),
        f("Vqd", "Напряжение по оси q, второй канал", "q-axis voltage, second channel", null, Likely),
        f("AQ", "Ток по оси q", "q-axis current", "А", Likely),
        f("AD", "Ток по оси d", "d-axis current", "А", Likely),
        f("AI", "Ток, третий канал", "Current, third channel", "А", Guess),
        f("AP", "Оценка тока по нагреву: спадает после нагрузки", "Thermal current estimate: decays after load", null, Likely),
        f("Bem", "Противо-ЭДС, растёт со скоростью", "Back-EMF, rises with speed", null, Likely),
        f("ChgAD", "АЦП зарядного входа", "Charger input ADC", null, Likely),
        f("CdA", "Канал АЦП, тот же что page 0/4 @63", "ADC channel, same as page 0/4 @63", null, Likely),
        f("LDpp", "Растёт со скоростью, знак по направлению", "Rises with speed, signed by direction", null, Guess),
        f("MdKM", "Всегда 0 во всех захватах", "Zero in every capture", null, Confirmed),
        f("GC", "Счётчик простоя: +5 за запись в покое", "Idle counter: +5 per record at rest", null, Likely),
        f("CC", "Всегда 0 во всех захватах", "Zero in every capture", null, Confirmed),
        f("CM", "Всегда 0 во всех захватах", "Zero in every capture", null, Confirmed),
        f("Lm1", "Всегда 0 во всех захватах", "Zero in every capture", null, Confirmed),
        f("RA", "Небольшое целое, знак меняется", "Small signed integer", null, Guess),
        f("Vpp", "Пик напряжения шины", "Bus voltage peak", "В", Likely),
        f("Vnp", "Отрицательный пик напряжения шины", "Bus voltage negative peak", "В", Likely),
        f("Vmx", "Максимум напряжения шины", "Bus voltage maximum", "В", Likely),
        f("Vmi", "Минимум напряжения шины", "Bus voltage minimum", "В", Likely),
        f("Vp", "Константа 81123.5 во всех захватах", "Constant 81123.5 in every capture", null, Confirmed),
        f("U1", "Не используется, всегда 0", "Unused, always 0", null, Confirmed),
        f("U2", "Не используется, всегда 0", "Unused, always 0", null, Confirmed),
        f("U3", "Не используется, всегда 0", "Unused, always 0", null, Confirmed),
        f("U4", "Не используется, всегда 0", "Unused, always 0", null, Confirmed),
        f("U5", "Не используется, всегда 0", "Unused, always 0", null, Confirmed),
        f("Cci", "Температура мотора", "Motor temperature", "°C", Confirmed),
        f("Cma", "Медленная тепловая масса: +0.16 °C там, где обмотка +7.3", "Slow thermal mass: +0.16 °C where the winding gained 7.3", null, Confirmed),
        f("CTr", "Сырой АЦП термистора, обратен Cci", "Raw thermistor ADC, inverse of Cci", null, Confirmed),
        f("Wht", "Потреблено за сессию", "Consumed this session", "Втч", Likely),
        f("Wcm", "Потреблено, второй счётчик", "Consumed, second counter", "Втч", Likely),
        f("Wma", "Максимум мощности", "Peak power", null, Guess),
        f("mWH", "Милливатт-часы, печатается дважды", "Milliwatt-hours, printed twice", null, Likely),
        f("Top", "Верхний предел контура", "Loop upper limit", null, Guess),
        f("Cnt", "Счётчик", "Counter", null, Guess),
        f("TA", "Ток, канал A", "Current, channel A", "А", Guess),
        f("FA", "Ток, канал F", "Current, channel F", "А", Guess),
        f("IA", "Ток, канал I", "Current, channel I", "А", Guess),
        f("LwC", "Нижний предел тока", "Lower current limit", null, Guess),
        f("Cres", "Сопротивление, вычисленное", "Computed resistance", null, Guess),
        f("Gres", "Сопротивление, второй канал", "Resistance, second channel", null, Guess),
        f("Asc", "Ток, оценка", "Current estimate", "А", Guess),
        f("Vgd", "Напряжение драйвера затворов", "Gate driver voltage", "В", Likely),
        f("OfC", "Смещение тока", "Current offset", null, Guess),
        f("Ha", "Состояние датчиков Холла", "Hall sensor state", null, Likely),
        f("Pole", "Электрическая позиция или номер пары полюсов", "Electrical position or pole pair index", null, Likely),
        f("rAB", "Сопротивление обмотки A-B", "A-B winding resistance", null, Guess),
        f("Dif", "Разность", "Difference", null, Guess),
        f("HPS", "Шаги датчиков Холла", "Hall steps", null, Guess),
        f("Di", "Отладочный счётчик", "Debug counter", null, Guess),
        f("JA", "Ток, канал J", "Current, channel J", null, Guess),
        f("ApS", "Сырой отсчёт токового датчика фазы A", "Raw phase A current sense", null, Likely),
        f("BpS", "Сырой отсчёт токового датчика фазы B", "Raw phase B current sense", null, Likely),
        f("CpS", "Сырой отсчёт токового датчика фазы C", "Raw phase C current sense", null, Likely),
        f("BC", "Смещение нуля АЦП фазы B, 32768 в покое", "Phase B ADC zero offset, 32768 at rest", null, Likely),
        f("CD", "Накопитель АЦП фазы C", "Phase C ADC accumulator", null, Likely),
        f("BD", "Накопитель АЦП фазы B", "Phase B ADC accumulator", null, Likely),
        f("Dir", "Направление вращения", "Rotation direction", null, Confirmed),
        f("SDr", "Заданное направление", "Commanded direction", null, Likely),
        f("isH", "Признак работы по датчикам Холла", "Hall-driven flag", null, Likely),
        f("DS", "Накопитель, большие значения", "Accumulator, large values", null, Guess),
        f("6Dpp", "Шесть шагов на электрический оборот", "Six steps per electrical revolution", null, Guess),
        f("HdHz", "Частота по датчикам Холла", "Hall-derived frequency", "Гц", Likely),
        f("DerC", "Счётчик ошибок производной", "Derivative error counter", null, Guess),
        f("Her8", "Счётчик ошибок датчиков Холла", "Hall error counter", null, Likely),
        f("dpOis", "Счётчик рассогласования", "Mismatch counter", null, Guess),
        f("fyOis", "Счётчик рассогласования", "Mismatch counter", null, Guess),
        f("diOis", "Счётчик рассогласования", "Mismatch counter", null, Guess),
        f("di1", "Отладочный вход 1", "Debug input 1", null, Guess),
        f("di2", "Отладочный вход 2", "Debug input 2", null, Guess),
        f("AX", "Акселерометр X", "Accelerometer X", null, Confirmed),
        f("AY", "Акселерометр Y", "Accelerometer Y", null, Confirmed),
        f("AZ", "Акселерометр Z, около 1000 в покое", "Accelerometer Z, about 1000 at rest", null, Confirmed),
        f("GX", "Гироскоп X", "Gyroscope X", null, Likely),
        f("GY", "Гироскоп Y", "Gyroscope Y", null, Likely),
        f("GZ", "Гироскоп Z; прошивка печатает это имя дважды", "Gyroscope Z; the firmware prints this name twice", null, Confirmed),
        f("GGY", "Гироскоп Y, фильтрованный", "Gyroscope Y, filtered", null, Likely),
        f("ASqt", "Норма акселерометра", "Accelerometer magnitude", null, Likely),
        f("RSqt", "Норма угловой скорости", "Angular rate magnitude", null, Likely),
        f("q0", "Кватернион ориентации, w", "Attitude quaternion, w", null, Likely),
        f("q1", "Кватернион ориентации, x", "Attitude quaternion, x", null, Likely),
        f("q2", "Кватернион ориентации, y", "Attitude quaternion, y", null, Likely),
        f("q3", "Кватернион ориентации, z", "Attitude quaternion, z", null, Likely),
        f("p", "Наклон вперёд-назад", "Pitch", null, Likely),
        f("r", "Наклон боковой", "Roll", null, Likely),
        f("y", "Курс", "Yaw", null, Likely),
        f("ex", "Ошибка регулятора по X", "Controller error, X", null, Guess),
        f("ey", "Ошибка регулятора по Y", "Controller error, Y", null, Guess),
        f("ez", "Ошибка регулятора по Z", "Controller error, Z", null, Guess),
        f("Kp", "Пропорциональный коэффициент", "Proportional gain", null, Likely),
        f("Kg", "Коэффициент регулятора", "Controller gain", null, Guess),
        f("Ka", "Коэффициент регулятора", "Controller gain", null, Guess),
        f("Kc", "Коэффициент регулятора", "Controller gain", null, Guess),
        f("iukp", "Интегратор, пропорциональная часть", "Integrator, proportional part", null, Guess),
        f("iuki", "Интегратор, интегральная часть", "Integrator, integral part", null, Guess),
        f("Ptb", "Наклон назад, tilt-back", "Tilt-back", null, Likely),
        f("PAref", "Задание угла педалей", "Pedal angle setpoint", null, Likely),
        f("Rtc", "Часы колеса, unix-время", "Wheel clock, unix time", "с", Confirmed),
        f("LiC", "Предел тока", "Current limit", null, Likely),
        f("OmC", "Предел, второй канал", "Limit, second channel", null, Guess),
        f("MP", "Отладочная маска", "Debug mask", null, Guess),
        f("fMS", "Счётчик миллисекунд", "Millisecond counter", null, Guess),
        f("tCNT", "Счётчик", "Counter", null, Guess),
        f("TeT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("ObT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("obtT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("FyT", "Всегда 0", "Always 0", null, Confirmed),
        f("GdcC", "Счётчик", "Counter", null, Guess),
        f("6TcC", "Счётчик", "Counter", null, Guess),
        f("SkM", "Пробег сессии", "Session distance", "км", Likely),
        f("TkM", "Пробег всего", "Total distance", "км", Likely),
        f("Rnd", "Разрядность АЦП, 4095", "ADC full scale, 4095", null, Likely),
        f("RC", "Счётчик", "Counter", null, Guess),
        f("Off", "Смещение", "Offset", null, Guess),
        f("OmT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("NlT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("HdT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("HeT", "Температура, канал не заведён: всегда 0", "Temperature channel, unwired: always 0", null, Confirmed),
        f("BajT", "Признак, 0 или 1", "Flag, 0 or 1", null, Confirmed),
        f("BtL", "Константа 8111", "Constant 8111", null, Confirmed),
        f("BtR", "Константа 8111", "Constant 8111", null, Confirmed),
        f("BtS", "Константа 81111", "Constant 81111", null, Confirmed),
        f("AOs", "Смещение нуля канала A", "Channel A zero offset", null, Likely),
        f("BOs", "Смещение нуля канала B", "Channel B zero offset", null, Likely),
        f("COs", "Смещение нуля канала C", "Channel C zero offset", null, Likely),
        f("DOs", "Смещение нуля канала D", "Channel D zero offset", null, Likely),
        f("AD16T", "Канал АЦП 16, температура", "ADC channel 16, temperature", null, Likely),
        f("AD17R", "Канал АЦП 17, сопротивление", "ADC channel 17, resistance", null, Likely),
        f("NxtRdy", "Готовность следующей записи лога", "Next log record ready", null, Likely),
        f("RxN", "Принято записей", "Records received", null, Guess),
        f("WtN", "Записано записей", "Records written", null, Guess),
        f("PgIdx", "Индекс страницы флеша", "Flash page index", null, Likely),
        f("EvIdx", "Индекс события", "Event index", null, Likely),
        f("ExiEvN", "Число событий выхода", "Exit event count", null, Guess),
        f("Flock", "Блокировка флеша", "Flash lock", null, Likely),
        f("PgEvN", "Число событий страницы", "Page event count", null, Guess),
        f("LsVol", "Объём файловой системы", "Filesystem volume", null, Likely),
        f("HzPid", "Частота контура управления, 499 Гц", "Control loop rate, 499 Hz", "Гц", Confirmed),
        f("HzAdc", "Частота АЦП, 10 кГц", "ADC rate, 10 kHz", "Гц", Confirmed),
        f("HzF10", "Задача 10 Гц", "10 Hz task", "Гц", Confirmed),
        f("HzF25", "Задача 25 Гц", "25 Hz task", "Гц", Confirmed),
        f("HzF50", "Задача 50 Гц", "50 Hz task", "Гц", Confirmed),
        f("HzF5K", "Задача 5 кГц", "5 kHz task", "Гц", Confirmed),
        f("HzWav", "Задача генерации волны", "Waveform task", "Гц", Likely),
        f("dHzDTE", "Частота DTE", "DTE rate", "Гц", Guess),
        f("U", "Загрузка CPU этой задачей", "CPU load of this task", "%", Confirmed),
        f("Mx", "Максимальная ячейка", "Highest cell", "мВ", Confirmed),
        f("Mi", "Минимальная ячейка", "Lowest cell", "мВ", Confirmed),
        f("BL", "Маска балансировки, шесть байт", "Balancing mask, six bytes", null, Likely),
        f("Btn", "Кнопка", "Button", null, Likely),
        f("Pbtn", "Кнопка, предыдущее состояние", "Button, previous state", null, Likely),
        f("RxS", "Принято по UART", "UART bytes received", null, Likely),
        f("RxR", "Ошибок приёма", "Receive errors", null, Guess),
        f("Len", "Длина кадра", "Frame length", null, Likely),
        f("Ncnt", "Счётчик кадров", "Frame counter", null, Likely),
        f("type", "Тип кадра", "Frame type", null, Likely),
        f("NoLV", "Признак низкого напряжения", "Low-voltage flag", null, Guess),
        f("DWTT", "Счётчик циклов DWT", "DWT cycle counter", null, Likely),
        f("U0RxId", "Индекс приёма UART0", "UART0 receive index", null, Likely),
        f("U0TxId", "Индекс передачи UART0", "UART0 transmit index", null, Likely),
        f("U0RxDm", "DMA приёма UART0", "UART0 receive DMA", null, Likely),
        f("Vb", "Напряжение, канал b", "Voltage, channel b", "В", Guess),
        f("Vd", "Напряжение, канал d", "Voltage, channel d", "В", Guess),
        f("Vf", "Напряжение, канал f", "Voltage, channel f", "В", Guess),
        f("Vn", "Напряжение, канал n", "Voltage, channel n", "В", Guess),
        f("Vum", "Напряжение, сумма", "Voltage, sum", "В", Guess),
        f("Vdm", "Напряжение, разность", "Voltage, difference", "В", Guess),
        f("lAD", "АЦП, левый", "ADC, left", null, Likely),
        f("rAD", "АЦП, правый", "ADC, right", null, Likely),
        f("Het", "Счётчик", "Counter", null, Guess),
        f("AD0", "Канал АЦП 0", "ADC channel 0", null, Likely),
        f("AD1", "Канал АЦП 1", "ADC channel 1", null, Likely),
        f("AD2", "Канал АЦП 2", "ADC channel 2", null, Likely),
        f("AD3", "Канал АЦП 3", "ADC channel 3", null, Likely),
        f("AD4", "Канал АЦП 4", "ADC channel 4", null, Likely),
        f("AD5", "Канал АЦП 5", "ADC channel 5", null, Likely),
        f("AD6", "Канал АЦП 6", "ADC channel 6", null, Likely),
        f("AD7", "Канал АЦП 7", "ADC channel 7", null, Likely),
        f("AD8", "Канал АЦП 8", "ADC channel 8", null, Likely),
        f("AD9", "Канал АЦП 9", "ADC channel 9", null, Likely),
        f("iAD0", "АЦП ток, канал 0", "ADC current, channel 0", null, Guess),
        f("iAD1", "АЦП ток, канал 1", "ADC current, channel 1", null, Guess),
        f("iAD2", "АЦП ток, канал 2", "ADC current, channel 2", null, Guess),
        f("iAD4", "АЦП ток, канал 4", "ADC current, channel 4", null, Guess),
        f("iAD8", "АЦП ток, канал 8", "ADC current, channel 8", null, Guess),
        f("iAD9", "АЦП ток, канал 9", "ADC current, channel 9", null, Guess),
        f("hAD0", "АЦП верхний, канал 0", "ADC high, channel 0", null, Guess),
        f("hAD1", "АЦП верхний, канал 1", "ADC high, channel 1", null, Guess),
        f("hAD2", "АЦП верхний, канал 2", "ADC high, channel 2", null, Guess),
        f("hAD4", "АЦП верхний, канал 4", "ADC high, channel 4", null, Guess),
        f("hAD8", "АЦП верхний, канал 8", "ADC high, channel 8", null, Guess),
        f("hAD9", "АЦП верхний, канал 9", "ADC high, channel 9", null, Guess),
        f("cAD0", "АЦП ячейка, канал 0", "ADC cell, channel 0", null, Guess),
        f("cAD1", "АЦП ячейка, канал 1", "ADC cell, channel 1", null, Guess),
        f("cAD2", "АЦП ячейка, канал 2", "ADC cell, channel 2", null, Guess),
        f("cAD4", "АЦП ячейка, канал 4", "ADC cell, channel 4", null, Guess),
        f("cAD8", "АЦП ячейка, канал 8", "ADC cell, channel 8", null, Guess),
        f("cAD9", "АЦП ячейка, канал 9", "ADC cell, channel 9", null, Guess),
        f("01", "Напряжение ячейки 1", "Cell 1 voltage", "мВ", Confirmed),
        f("02", "Напряжение ячейки 2", "Cell 2 voltage", "мВ", Confirmed),
        f("03", "Напряжение ячейки 3", "Cell 3 voltage", "мВ", Confirmed),
        f("04", "Напряжение ячейки 4", "Cell 4 voltage", "мВ", Confirmed),
        f("05", "Напряжение ячейки 5", "Cell 5 voltage", "мВ", Confirmed),
        f("06", "Напряжение ячейки 6", "Cell 6 voltage", "мВ", Confirmed),
        f("07", "Напряжение ячейки 7", "Cell 7 voltage", "мВ", Confirmed),
        f("08", "Напряжение ячейки 8", "Cell 8 voltage", "мВ", Confirmed),
        f("09", "Напряжение ячейки 9", "Cell 9 voltage", "мВ", Confirmed),
        f("10", "Напряжение ячейки 10", "Cell 10 voltage", "мВ", Confirmed),
        f("11", "Напряжение ячейки 11", "Cell 11 voltage", "мВ", Confirmed),
        f("12", "Напряжение ячейки 12", "Cell 12 voltage", "мВ", Confirmed),
        f("13", "Напряжение ячейки 13", "Cell 13 voltage", "мВ", Confirmed),
        f("14", "Напряжение ячейки 14", "Cell 14 voltage", "мВ", Confirmed),
        f("15", "Напряжение ячейки 15", "Cell 15 voltage", "мВ", Confirmed),
        f("16", "Напряжение ячейки 16", "Cell 16 voltage", "мВ", Confirmed),
        f("17", "Напряжение ячейки 17", "Cell 17 voltage", "мВ", Confirmed),
        f("18", "Напряжение ячейки 18", "Cell 18 voltage", "мВ", Confirmed),
        f("19", "Напряжение ячейки 19", "Cell 19 voltage", "мВ", Confirmed),
        f("20", "Напряжение ячейки 20", "Cell 20 voltage", "мВ", Confirmed),
        f("21", "Напряжение ячейки 21", "Cell 21 voltage", "мВ", Confirmed),
        f("22", "Напряжение ячейки 22", "Cell 22 voltage", "мВ", Confirmed),
        f("23", "Напряжение ячейки 23", "Cell 23 voltage", "мВ", Confirmed),
        f("24", "Напряжение ячейки 24", "Cell 24 voltage", "мВ", Confirmed),
        f("25", "Напряжение ячейки 25", "Cell 25 voltage", "мВ", Confirmed),
        f("26", "Напряжение ячейки 26", "Cell 26 voltage", "мВ", Confirmed),
        f("27", "Напряжение ячейки 27", "Cell 27 voltage", "мВ", Confirmed),
        f("28", "Напряжение ячейки 28", "Cell 28 voltage", "мВ", Confirmed),
        f("29", "Напряжение ячейки 29", "Cell 29 voltage", "мВ", Confirmed),
        f("30", "Напряжение ячейки 30", "Cell 30 voltage", "мВ", Confirmed),
        f("31", "Напряжение ячейки 31", "Cell 31 voltage", "мВ", Confirmed),
        f("32", "Напряжение ячейки 32", "Cell 32 voltage", "мВ", Confirmed),
        f("33", "Напряжение ячейки 33", "Cell 33 voltage", "мВ", Confirmed),
        f("34", "Напряжение ячейки 34", "Cell 34 voltage", "мВ", Confirmed),
        f("35", "Напряжение ячейки 35", "Cell 35 voltage", "мВ", Confirmed),
        f("36", "Напряжение ячейки 36", "Cell 36 voltage", "мВ", Confirmed),
        f("Rqt", "Запросов к BMS", "BMS requests", null, Likely),
        f("RxM", "Ответов от BMS", "BMS replies", null, Likely),
        f("Vbu", "Напряжение шины BMS, совпадает с V", "BMS bus voltage, matches V", "В", Likely),
        f("Vsc", "Напряжение шины, второй канал", "Bus voltage, second channel", "В", Likely),
        f("Aa", "Ток BMS, канал a", "BMS current, channel a", "А", Likely),
        f("Ac", "Ток BMS, канал c", "BMS current, channel c", "А", Likely),
        f("Ap", "Ток BMS, пиковый", "BMS current, peak", "А", Guess),
        f("Aco", "Накопленный заряд", "Accumulated charge", null, Guess),
        f("BLN", "Число балансируемых ячеек", "Cells being balanced", null, Guess),
        f("StcC", "Счётчик состояния, печатается дважды", "State counter, printed twice", null, Likely),
        f("StmV", "Напряжение состояния, печатается дважды", "State voltage, printed twice", "мВ", Guess),
        f("T0", "Сырой отсчёт термистора BMS 0", "Raw BMS thermistor 0", null, Likely),
        f("T1", "Сырой отсчёт термистора BMS 1", "Raw BMS thermistor 1", null, Likely),
        f("T2", "Сырой отсчёт термистора BMS 2", "Raw BMS thermistor 2", null, Likely),
        f("T3", "Сырой отсчёт термистора BMS 3", "Raw BMS thermistor 3", null, Likely),
        f("T4", "Сырой отсчёт термистора BMS 4", "Raw BMS thermistor 4", null, Likely),
        f("T5", "Сырой отсчёт термистора BMS 5", "Raw BMS thermistor 5", null, Likely),
        f("Cs", "Счётчик", "Counter", null, Guess),
        f("Os", "Счётчик", "Counter", null, Guess),
        f("Cc", "Счётчик", "Counter", null, Guess),
        f("Co", "Счётчик, печатается дважды", "Counter, printed twice", null, Guess),
        f("Vo", "Напряжение, канал o", "Voltage, channel o", null, Guess),
        f("BrS", "Реле или тормоз, состояние", "Relay or brake, state", null, Guess),
        f("BrR", "Реле или тормоз, второй канал", "Relay or brake, second channel", null, Guess),
        f("rM", "Режим", "Mode", null, Guess),
        f("T", "Счётчик", "Counter", null, Guess),
        f("S", "Счётчик", "Counter", null, Guess),
        f("A", "Одиночный канал, назначение зависит от страницы", "Single channel, meaning depends on the page", null, Guess),
        f("B", "Одиночный канал, назначение зависит от страницы", "Single channel, meaning depends on the page", null, Guess),
        f("C", "Одиночный канал, назначение зависит от страницы", "Single channel, meaning depends on the page", null, Guess),
        f("R", "Одиночный канал АЦП", "Single ADC channel", null, Guess),
        f("Se", "Одиночный канал АЦП", "Single ADC channel", null, Guess),
        f("Pat", "Признак", "Flag", null, Guess),
        f("Ple", "Признак", "Flag", null, Guess),
        f("Psl", "Признак", "Flag", null, Guess),
        f("bit", "Битовая маска", "Bit mask", null, Guess),
        f("cR", "Сопротивление, вычисленное", "Computed resistance", null, Guess),
        f("mO", "Смещение", "Offset", null, Guess),
        f("uEc", "Счётчик ошибок", "Error counter", null, Guess),
    )

    private val byTag: Map<String, LeaperKimStrField> = all.associateBy { it.tag }

    fun describe(tag: String): LeaperKimStrField? = byTag[tag]
}
